name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci --force
    - name: Install Allure
      run: |
        sudo apt-get install default-jre-headless
        sudo apt-get install allure
        npm i -D @playwright/test allure-playwright --force
        wget https://github.com/allure-framework/allure2/releases/download/2.33.0/allure_2.33.0-1_all.deb
        sudo dpkg -i allure_2.33.0-1_all.deb 
    - name: Setup application under test
      run: 
        cd pw-practice-app
        npm install --force
        cd ..
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps --force
    - name: Run Playwright tests
      env:
        CONDUIT_EMAIL: ${{ secrets.CONDUIT_EMAIL }}
        CONDUIT_PASSWORD: ${{ secrets.CONDUIT_PASSWORD }}
      run: npx playwright test --project=chromium
      continue-on-error: true
    - name: Allure report
      run: allure generate allure-results -o allure-results --clean
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-results/
        retention-days: 30
