name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Setup application under test
      run: | 
        wget https://github.com/bondar-artem/pw-practice-app/archive/refs/heads/master.zip
        unzip pw-practice-app-master.zip
        cd pw-practice-app-master
        npm install --force
        npm start &
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        CONDUIT_EMAIL: ${{ secrets.CONDUIT_EMAIL }}
        CONDUIT_PASSWORD: ${{ secrets.CONDUIT_PASSWORD }}
      run: npx playwright test workingWithApis.spec.ts --project=Chromium
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
